all:
  vars:
    cloud_provider: "gcp"
    prefix: "geo-3k"
    project_name: "gitlab-qa-distribution"
    ansible_user: "sa_117401977288730813591"
    service_account_file: "../keys/distribution/gitlab-qa-distribution-sa.json"
    ansible_ssh_private_key_file: "../keys/distribution/gitlab-qa-distribution-ssh"
    external_url: "http://34.91.88.231"
    install_patroni: false
    gitlab_root_password_file: "../keys/distribution/gitlab_root_password"