all:
  vars:
    prefix: "gitlab-qa-2k"
    project_name: "gitlab-qa-2k-ca9f9e"
    ansible_user: "sa_117740835761395319154"
    ansible_ssh_private_key_file: "../secrets/gitlab-qa-gcp-ssh"
    external_url: "http://2k.testbed.gitlab.net"
