---
- name: Mount GitLab NFS
  mount:
    fstype: nfs
    opts: defaults,nofail,lookupcache=positive
    state: mounted
    src: "{{ gitlab_nfs_ip }}:{{ gitlab_nfs_path }}"
    path: "{{ gitlab_nfs_path }}"
  tags: nfs

- name: Configure SSH Fast Lookup
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item.setting }}="
    line: "{{ item.setting }}={{ item.value }}"
  with_items: 
    - { setting: 'AuthorizedKeysCommand', value: '/opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell-authorized-keys-check git %u %k'}
    - { setting: 'AuthorizedKeysCommandUser', value: 'git'}

- name: Create the /etc/gitlab/gitlab.rb file
  template:
    src: templates/gitlab-rails.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags: gitlab_template

- name: Download secrets file
  shell: gsutil cp gs://gitlab-conf-storage/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true
  tags: secrets

- name: Reconfigure GitLab Primary
  shell: gitlab-ctl reconfigure
  tags: reconfigure
  when: "'gitlab_rails_primary' in group_names"

- name: Upload secrets file if missing
  shell: gsutil cp -n /etc/gitlab/gitlab-secrets.json gs://gitlab-conf-storage
  tags: secrets
  run_once: true

- name: Hot Reload GitLab Primary
  shell: gitlab-ctl hup puma && gitlab-ctl hup sidekiq
  tags: reload
  when: "'gitlab_rails_primary' in group_names"

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r
  when: 
    - "'gitlab_rails_secondary' in group_names"

- name: Reconfigure GitLab Secondaries
  shell: gitlab-ctl reconfigure
  tags: reconfigure
  when: "'gitlab_rails_secondary' in group_names"

- name: Hot Reload GitLab Secondaries
  shell: gitlab-ctl hup puma && gitlab-ctl hup sidekiq
  tags: reload
  when: "'gitlab_rails_secondary' in group_names"
