---
- name: Create the /etc/gitlab/gitlab.rb file
  template:
    src: templates/gitlab-rails.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags: gitlab_template

- name: Reconfigure GitLab Primary
  shell: gitlab-ctl reconfigure
  tags: reconfigure
  when: "'gitlab_rails_primary' in group_names"

#- name: Copy GitLab Primary Secrets to Secondaries
#  synchronize: src=/etc/gitlab/gitlab-secrets.json dest=/etc/gitlab/gitlab-secrets.json
#  delegate_to: "{{ item }}"
#  tags: copy
#  with_items: "{{ groups['gitlab_rails_secondary'] }}"
#  when: "'gitlab_rails_primary' in group_names"

- name: Store file 
  fetch:
    src: /etc/gitlab/gitlab-secrets.json
    dest: /tmp/gitlab-secrets.json
    flat: yes
  tags: copy
  when: "'gitlab_rails_primary' in group_names"

- name: Copy file
  copy:
    src: /tmp/gitlab-secrets.json
    dest: /etc/gitlab/gitlab-secrets.json
  tags: copy
  when: 
    - "'gitlab_rails_secondary' in group_names"

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r
  when: 
    - "'gitlab_rails_secondary' in group_names"

- name: Reconfigure GitLab Secondaries
  shell: gitlab-ctl reconfigure
  tags: reconfigure
  when: "'gitlab_rails_secondary' in group_names"

#- name: Database Setup
#  command: gitlab-rake gitlab:setup
#  when: 
#    - "'gitlab_rails_primary' in group_names"