---
- name: Create the /etc/gitlab/gitlab.rb file
  template:
    src: templates/gitlab-rails.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags: gitlab_template

- name: Reconfigure GitLab Primary
  shell: gitlab-ctl reconfigure
  tags: reconfigure
  when: "'gitlab_rails_primary' in group_names"

- name: Hot Reload GitLab Primary
  shell: gitlab-ctl hup unicorn && gitlab-ctl hup sidekiq
  tags: reload
  when: "'gitlab_rails_primary' in group_names"

- name: Store secrets file from primary
  fetch:
    src: /etc/gitlab/gitlab-secrets.json
    dest: /tmp/gitlab-secrets.json
    flat: yes
  tags: copy
  when: "'gitlab_rails_primary' in group_names"

- name: Copy secrets file to secondaries
  copy:
    src: /tmp/gitlab-secrets.json
    dest: /etc/gitlab/gitlab-secrets.json
  tags: copy
  when: 
    - "'gitlab_rails_secondary' in group_names"

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r
  when: 
    - "'gitlab_rails_secondary' in group_names"

- name: Reconfigure GitLab Secondaries
  shell: gitlab-ctl reconfigure
  tags: reconfigure
  when: "'gitlab_rails_secondary' in group_names"

- name: Hot Reload GitLab Secondaries
  shell: gitlab-ctl hup unicorn && gitlab-ctl hup sidekiq
  tags: reload
  when: "'gitlab_rails_secondary' in group_names"
