---
- name: Mount GitLab NFS
  mount:
    fstype: nfs
    opts: defaults,nofail,lookupcache=positive
    state: mounted
    src: "{{ gitlab_nfs_int_ip }}:{{ gitlab_nfs_path }}"
    path: "{{ gitlab_nfs_path }}"
  tags: nfs

- name: Configure SSH Fast Lookup
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item.setting }}="
    line: "{{ item.setting }}={{ item.value }}"
  with_items: 
    - { setting: 'AuthorizedKeysCommand', value: '/opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell-authorized-keys-check git %u %k'}
    - { setting: 'AuthorizedKeysCommandUser', value: 'git'}

- name: Download secrets files
  shell: |
    gsutil cp gs://{{ gitlab_secrets_storage }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true
    gsutil cp gs://{{ gitlab_secrets_storage }}/{{ serviceaccount_filename }} {{ serviceaccount_path }} 2>/dev/null || true
  tags: secrets

- name: Setup GitLab config file for DB Configure
  template:
    src: templates/gitlab-rails.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  vars:
    db_migrate: true
  register: result
  retries: 3
  until: result is success
  tags: reconfigure
  when: "'gitlab_rails_primary' in group_names"

- name: Reconfigure GitLab Primary for DB
  shell: gitlab-ctl reconfigure
  tags: reconfigure
  when: "'gitlab_rails_primary' in group_names"

- name: Setup GitLab config file
  template:
    src: templates/gitlab-rails.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  register: result
  retries: 3
  until: result is success
  tags: reconfigure

- name: Reconfigure GitLab Primary
  shell: gitlab-ctl reconfigure
  tags: reconfigure
  when: "'gitlab_rails_primary' in group_names"

- name: Restart GitLab Primary
  command: gitlab-ctl restart
  register: result
  retries: 2
  until: result is success
  tags:
    - reconfigure
    - restart
  when: "'gitlab_rails_primary' in group_names"

- name: Reconfigure GitLab Secondaries
  shell: gitlab-ctl reconfigure
  tags: reconfigure
  when: "'gitlab_rails_secondary' in group_names"

- name: Restart GitLab Secondaries
  command: gitlab-ctl restart
  register: result
  retries: 2
  until: result is success
  tags:
    - reconfigure
    - restart
  when: "'gitlab_rails_secondary' in group_names"

- name: Upload secrets file if missing
  shell: "gsutil cp -n /etc/gitlab/gitlab-secrets.json gs://{{ gitlab_secrets_storage }}"
  tags: secrets
  run_once: true

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r
