all:
  vars:
    prefix: "gitlab-qa-5k"
    project_name: "gitlab-qa-5k-0ee8fa"
    ansible_user: "sa_117413207790422770954"
    ansible_ssh_private_key_file: "../secrets/gitlab-qa-gcp-ssh"
    external_url: "http://5k.testbed.gitlab.net"
    redis_separated: false
