---
- name: Create the /etc/gitlab/gitlab.rb file
  template:
    src: templates/sidekiq.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags:
    - gitlab_template

- name: Copy secrets file to sidekiqs
  copy:
    src: /tmp/gitlab-secrets.json
    dest: /etc/gitlab/gitlab-secrets.json
  tags: copy

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r

- name: Reconfigure GitLab
  shell: gitlab-ctl reconfigure
  tags:
    - reconfigure

- name: Hot Reload Sidekiq 
  shell: gitlab-ctl hup sidekiq
  tags: reload
