---
- name: Mount GitLab NFS
  mount:
    fstype: nfs
    opts: defaults,nofail,lookupcache=positive
    state: mounted
    src: "{{ gitlab_nfs_ip }}:{{ gitlab_nfs_path }}"
    path: "{{ gitlab_nfs_path }}"
  tags: nfs

- name: Configure SSH Fast Lookup
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item.setting }}="
    line: "{{ item.setting }}={{ item.value }}"
  with_items: 
    - { setting: 'AuthorizedKeysCommand', value: '/opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell-authorized-keys-check git %u %k'}
    - { setting: 'AuthorizedKeysCommandUser', value: 'git'}

- name: Create the /etc/gitlab/gitlab.rb file
  template:
    src: templates/sidekiq.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags:
    - gitlab_template

- name: Download secrets file
  shell: "gsutil cp gs://{{ gitlab_conf_storage }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
  tags: secrets

- name: Reconfigure GitLab
  shell: gitlab-ctl reconfigure
  tags:
    - reconfigure

- name: Upload secrets file if missing
  shell: "gsutil cp -n /etc/gitlab/gitlab-secrets.json gs://{{ gitlab_conf_storage }}"
  tags: secrets
  run_once: true

- name: Hot Reload Sidekiq 
  shell: gitlab-ctl hup sidekiq
  tags: reload

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r
