---
- name: Create /etc/gitlab/gitlab.rb
  template:
    src: templates/consul.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags: reconfigure

- name: Download secrets file
  shell: "gsutil cp gs://{{ gitlab_secrets_storage }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
  tags: secrets

- name: Reconfigure Consul
  shell: gitlab-ctl reconfigure
  tags:
    - reconfigure

- name: Restart Consul
  command: gitlab-ctl restart
  tags:
    - reconfigure
    - restart

- name: Upload secrets file if missing
  shell: "gsutil cp -n /etc/gitlab/gitlab-secrets.json gs://{{ gitlab_secrets_storage }}"
  tags: secrets
  run_once: true

- name: Restart Consul
  command: gitlab-ctl restart consul
  when: gitlab_file.stat.exists

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r

- name: Store secrets file
  shell: "gsutil cp -n /etc/gitlab/gitlab-secrets.json gs://{{ gitlab_secrets_storage }}"
  tags: secrets
  run_once: true