---
- name: Mount GitLab NFS
  mount:
    fstype: nfs
    opts: defaults,nofail,lookupcache=positive
    state: mounted
    src: "{{ gitlab_nfs_int_ip }}:{{ gitlab_nfs_path }}"
    path: "{{ gitlab_nfs_path }}"
  tags: nfs

- name: Setup GitLab config file
  template:
    src: templates/consul.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags: reconfigure

- name: Check if custom config exists
  stat:
    path: "{{ consul_custom_config_file }}"
  delegate_to: localhost
  become: false
  tags: reconfigure
  register: consul_custom_config_file_path

- name: Copy custom GitLab config file
  copy:
    src: "{{ consul_custom_config_file }}"
    dest: "/etc/gitlab/gitlab.consul.custom.rb"
    mode: 0755
  tags: reconfigure
  when: consul_custom_config_file_path.stat.exists

- name: Copy secrets file from NFS
  shell: "cp {{ gitlab_nfs_path }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
  tags: secrets

- name: Stop Consul
  shell: gitlab-ctl stop consul
  tags:
    - reconfigure

- name: Clear old Consul data
  file:
    path: /var/opt/gitlab/consul/data
    state: absent
  tags:
    - reconfigure

- name: Reconfigure Consul
  shell: gitlab-ctl reconfigure
  tags:
    - reconfigure

- name: Restart Consul
  command: gitlab-ctl restart
  register: result
  retries: 2
  until: result is success
  tags:
    - reconfigure
    - restart

- name: Copy secrets file to NFS if missing
  shell: "cp -n /etc/gitlab/gitlab-secrets.json {{ gitlab_nfs_path }}"
  tags: secrets
  run_once: true

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r
