---
- name: Setup GitLab config file
  template:
    src: templates/monitor.gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  tags: reconfigure

- name: Download secrets file
  shell: "gsutil cp gs://{{ gitlab_secrets_storage }}/gitlab-secrets.json /etc/gitlab/gitlab-secrets.json 2>/dev/null || true"
  tags: secrets

- name: Create GitLab Quality Grafana dashboards directory
  file:
    path: /opt/gitlab-quality/dashboards
    state: directory
  tags: reconfigure

- name: Copy GitLab Quality Grafana dashboards
  copy:
    src: "{{ item }}"
    dest: "/opt/gitlab-quality/dashboards"
  with_fileglob:
    - files/*
  tags: reconfigure

- name: Reconfigure GitLab
  shell: gitlab-ctl reconfigure
  tags: reconfigure

- name: Restart Monitor
  shell: |
    gitlab-ctl stop
    pkill -f "/opt/gitlab/embedded/bin/prometheus[[:alnum:][:space:]\-]+" || echo "Prometheus is already stopped"
    gitlab-ctl start
  register: result
  retries: 2
  until: result is success
  tags:
    - reconfigure
    - restart

- name: Upload secrets file if missing
  shell: "gsutil cp -n /etc/gitlab/gitlab-secrets.json gs://{{ gitlab_secrets_storage }}"
  tags: secrets
  run_once: true

- name: Create skip-auto-reconfigure file
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: u=rw,g=r,o=r
