- name: Add Site Name - Add Geo secondary site to tracking db for Omnibus environments
  command: |
    gitlab-rails runner "GeoNode.find_or_create_by(name: '{{ geo_secondary_site_name }}', url: '{{geo_secondary_external_url }}', internal_url: '{{ geo_secondary_internal_url }}')"
  when:
    - ('gitlab_rails_primary' in group_names)
    - ( geo_primary_site_group_name in group_names)

- name: Add Site Name for Cloud Native Hybrid environments
  block:
    - name: Add Site Name - Configure kubeconfig credentials for Geo primary site
      become: false
      delegate_to: localhost
      run_once: true
      import_tasks: kubeconfig.yml
      vars:
        geo_site_prefix: "{{ geo_primary_site_prefix }}"
        geo_site_gcp_project: "{{ geo_primary_site_gcp_project if cloud_provider == 'gcp' else '' }}"
        geo_site_gcp_zone: "{{ geo_primary_site_gcp_zone if cloud_provider == 'gcp' else '' }}"
        geo_site_aws_region: "{{ geo_primary_site_aws_region if cloud_provider == 'aws' else '' }}"

    - name: Add Site Name - Add Geo secondary site to tracking db for Cloud Native Hybrid environments
      become: false
      delegate_to: localhost
      run_once: true
      kubernetes.core.k8s_exec:
        pod: "{{ task_runner_pod }}"
        namespace: "{{ gitlab_charts_release_namespace }}"
        command: |
          gitlab-rails runner "GeoNode.find_or_create_by(name: '{{ geo_secondary_site_name }}', url: '{{ geo_secondary_external_url }}', internal_url: '{{ geo_secondary_internal_url }}')"
  when: cloud_native_hybrid_geo
