all:
  vars:
    cloud_provider: "gcp"
    prefix: "gitlab-qa-3k"
    project_name: "gitlab-qa-3k-d0c40c"
    ansible_user: "sa_104607004321653710795"
    ansible_ssh_private_key_file: "../keys/performance/gitlab-qa-ssh"
    gitlab_license_file: "../keys/performance/Gitlab.gitlab-license"
    external_url: "http://3k.testbed.gitlab.net"
    install_patroni: true