plugin: aws_ec2
regions:
  - <aws_region>
filters:
  tag:gitlab_node_prefix: <environment_prefix>
keyed_groups:
  - key: tags.gitlab_node_type
    separator: ''
  - key: tags.gitlab_node_level
    separator: ''
hostnames:
  # List host by name instead of the default public ip
  - tag:Name
compose:
  # Return the public IP address of the box for connection
  # 'public_ip_address' is the correct value here and should not be replaced
  ansible_host: public_ip_address
