all:
  vars:
    # Ansible Settings
    ansible_user: "<ssh_username>" # Typically ubuntu or ec2-user
    ansible_ssh_private_key_file: "<private_ssh_key_path>"

    # Cloud Settings
    cloud_provider: "aws"
    aws_region: "<aws_region>"
    aws_allocation_ids: "<external_ip_allocation_id1>,<external_ip_allocation_id1>,<external_ip_allocation_id1>"

    # General Settings
    prefix: "<environment_prefix>"
    external_url: "<external_url>"
    external_ip: "<external_ip>"
    gitlab_license_file: "<gitlab_license_file_path>"
    cloud_native_hybrid_environment: true
    kubeconfig_setup: true

    # RDS Settings
    postgres_host: "<rds_url>"

    # Elasticache Settings
    redis_cache_host: "<elasticache_cache_url>"
    redis_persistent_host: "<elasticache_persistent_url>"

    # Load Balancer Settings
    internal_lb_host: "<nlb_internal_url>"

    # Passwords / Secrets
    gitlab_root_password: '<gitlab_root_password>'
    grafana_password: '<grafana_password>'
    postgres_password: '<postgres_password>'
    consul_database_password: '<consul_database_password>'
    gitaly_token: '<gitaly_token>'
    redis_password: '<redis_password>'
    praefect_external_token: '<praefect_external_token>'
    praefect_internal_token: '<praefect_internal_token>'
    praefect_postgres_password: '<praefect_postgres_password>'
