- name: Get License Plan
  uri:
    url: '{{ external_url_sanitised }}/api/v4/license'
    method: GET
    headers:
      PRIVATE-TOKEN: '{{ access_token_key }}'
    status_code: 200
    body_format: json
    return_content: true
  register: license_response

- name: Configure Ultimate License (if missing)
  uri:
    url: '{{ external_url_sanitised }}/api/v4/license'
    method: POST
    headers:
      PRIVATE-TOKEN: '{{ access_token_key }}'
    body:
      license: "{{ lookup('file', gitlab_license_file) }}"
    follow_redirects: all
    status_code: 200, 201
    body_format: json
    return_content: true
  register: configure_license_response
  when: license_response.json == None

- name: Save License Plan
  set_fact:
    gitlab_license_plan: '{{ configure_license_response.json.plan if license_response.json == None else license_response.json.plan }}'
