plugin: gcp_compute
projects:
  - gitlab-qa-25k-bc38fe
filters:
  - labels.gitlab_node_prefix = gitlab-qa-25k
keyed_groups:
  - key: labels.gitlab_node_type
    separator: ''
  - key: labels.gitlab_node_level
    separator: ''
scopes:
  - https://www.googleapis.com/auth/compute
service_account_file: ../keys/performance/serviceaccount-25k.json
auth_kind: serviceaccount
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP