geo_primary_site_gitlab_rails_nodename: "{{ (groups['geo_primary_site_gitlab_rails_primary'] | map('extract', hostvars, ['ansible_nodename']) | join('')) }}"
geo_secondary_site_gitlab_rails_nodename: "{{ (groups['geo_secondary_site_gitlab_rails_primary'] | map('extract', hostvars, ['ansible_nodename']) | join('')) }}"

geo_primary_site_name: "Primary Site - {{ hostvars[geo_primary_site_gitlab_rails_nodename]['labels']['gitlab_node_prefix'] }}"
geo_secondary_site_name: "Secondary Site - {{ hostvars[geo_secondary_site_gitlab_rails_nodename]['labels']['gitlab_node_prefix'] }}"

geo_secondary_site_postgres_group_name: "{{ 'geo_secondary_site_postgres_primary' if 'geo_secondary_site_postgres_primary' in groups else 'geo_secondary_site_gitlab_rails_primary' }}"
geo_secondary_site_postgres_int_ip: "{{
                                      (groups[geo_secondary_site_postgres_group_name] |
                                      map('extract', hostvars, ['networkInterfaces']) |
                                      map('first') |
                                      map(attribute='networkIP') |
                                      join(''))
                                    }}"

geo_primary_site_postgres_group_name: "{{ 'geo_primary_site_postgres_primary' if 'geo_primary_site_postgres_primary' in groups else 'geo_primary_site_gitlab_rails_primary' }}"
geo_primary_site_postgres_int_ip: "{{
                                    (groups[geo_primary_site_postgres_group_name] |
                                    map('extract', hostvars, ['networkInterfaces']) |
                                    map('first') |
                                    map(attribute='networkIP') |
                                    join(''))
                                  }}"

geo_secondary_site_rails_primary_int_ip: "{{
                                           (groups['geo_secondary_site_gitlab_rails_primary'] |
                                           map('extract', hostvars, ['networkInterfaces']) |
                                           map('first') |
                                           map(attribute='networkIP') |
                                           join(''))
                                         }}"

geo_secondary_site_rails_secondary_int_ips: "{{
                                              (groups['geo_secondary_site_gitlab_rails_secondary'] |
                                              map('extract', hostvars, ['networkInterfaces']) |
                                              map('first') |
                                              map(attribute='networkIP')) |
                                              list
                                              if 'geo_secondary_site_gitlab_rails_secondary' in groups else ''
                                            }}"

geo_secondary_site_sidekiq_primary_group_name: "{{ 'geo_secondary_site_sidekiq_primary' if 'geo_secondary_site_sidekiq_primary' in groups else 'geo_secondary_site_gitlab_rails_primary' }}"
geo_secondary_site_sidekiq_primary_int_ip: "{{
                                             (groups['geo_secondary_site_sidekiq_primary'] |
                                             map('extract', hostvars, ['networkInterfaces']) |
                                             map('first') |
                                             map(attribute='networkIP') |
                                             join(''))
                                           }}"

geo_secondary_site_sidekiq_secondary_int_ips: "{{
                                                (groups['geo_secondary_site_sidekiq_secondary'] |
                                                map('extract', hostvars, ['networkInterfaces']) |
                                                map('first') |
                                                map(attribute='networkIP')) |
                                                list
                                                if 'geo_secondary_site_sidekiq_secondary' in groups else ''
                                              }}"

tracking_db_md5_auth: "['{{ geo_secondary_site_rails_primary_int_ip }}/32'{% for ip in geo_secondary_site_rails_secondary_int_ips %}, '{{ ip }}/32'{% endfor %}, '{{ geo_secondary_site_sidekiq_primary_int_ip }}/32'{% for ip in geo_secondary_site_sidekiq_secondary_int_ips %}, '{{ ip }}/32'{% endfor %}]"
