- name: kubeconfig - Configure local kubeconfig to point to correct cluster
  vars:
    kubeconfig_setup: true
    prefix: "{{ geo_site_prefix }}"
    gcp_project: "{{ geo_site_gcp_project if cloud_provider == 'gcp' else '' }}"
    gcp_zone: "{{ geo_site_gcp_zone if cloud_provider == 'gcp' else '' }}"
    aws_region: "{{ geo_site_aws_region if cloud_provider == 'aws' else '' }}"
  include_role:
    name: gitlab-charts
    tasks_from: kubeconfig
    apply:
      become: false
      delegate_to: localhost
      run_once: true

- name: kubeconfig - Fetch task runner pod
  community.kubernetes.k8s_info:
    kind: Pod
    label_selectors:
      - app in (task-runner, toolbox)
  register: task_runner_info

- name: Save Task Runner pod name
  set_fact:
    task_runner_pod: "{{ task_runner_info | json_query('resources[0].metadata.name') }}"
