all:
  vars:
    cloud_provider: "azure"
    prefix: "gitlab-qa-10k"
    ansible_user: "gitlab-qa"
    ansible_ssh_private_key_file: "../keys/performance/gitlab-qa-ssh"
    gitlab_license_file: "../keys/performance/Gitlab.gitlab-license"
    external_url: "http://52.247.17.150"
