namespace: "gitlab"
name: "gitlab_environment_toolkit"
version: "2.4.0"
readme: "../README.md"
description: |
  The GitLab Environment Toolkit (GET) is a collection of tools to deploy and operate production
  GitLab instances based on our Reference Architectures, including automation of common day 2 tasks.
documentation: "https://gitlab.com/gitlab-org/gitlab-environment-toolkit#documentation"
issues: "https://gitlab.com/gitlab-org/gitlab-environment-toolkit/-/issues"
authors:
    - "GitLab Quality Enablement Team"
dependencies:
    "google.cloud": ">=1.0"
    "azure.azcollection": ">=1.10"
    "kubernetes.core": ">=2.0"
    "community.postgresql": ">=1.6"
license_file: '../LICENSE'
tags:
    - gitlab
    - gitlab_environment_toolkit
repository: "https://gitlab.com/gitlab-org/gitlab-environment-toolkit"
