---
- hosts: all:!ungrouped
  become: true

  tasks:
  - name: Uninstall GitLab package
    command: "{{ item }}"
    args:
      warn: false
    with_items:
      - apt-mark install gitlab-ee
      - apt-get remove gitlab-ee -y
    when:
      - omnibus_node

  - name: Uninstall any GitLab repositories
    command: "{{ item }}"
    args:
      warn: false
    with_items:
      - apt-add-repository -r https://packages.gitlab.com/gitlab/nightly-builds/ubuntu/
      - apt-add-repository -r https://packages.gitlab.com/gitlab/gitlab-ee/ubuntu/
    when:
      - omnibus_node
